### PR TITLE
Fix parsing of issuer country

### LINKED ISSUE #245: Wrong handling of Issuer CN fields in getIssuerCountry
## Describe the bug

The app calls `val keys = issuerX500Principal.name.split(",")` in the getIssuerCountryFunction. This does not handle escaped commas that are valid as per X509 spec. This makes the app crash on Slovenian certificates, as the issuer name is `C=SI, O=NIJZ\, National Institute of Public Health of Slovenia, OU=NIJZ eHealth, CN=Slovenian Digital Covid Certificate CSCA` with an indexOutOfBoundsException.

## Expected behaviour

The app should handle the escaped commas correctly.

## Steps to reproduce the issue

Scan a slovenian COVID certificate. Mine is available upon request on my email.

## Possible Fix

See how sanipasse fixed this: https://github.com/lovasoa/sanipasse/issues/72

### PR DESCRIPTION
**Pull request by craftbyte**
Closes #245

### CODE REVIEW

**Comment by stefanb** [comment]
Dear maintainers, please check this ASAP, so it gets included into various national forks, otherwise certificates issued in Slovenia 🇸🇮  will have validation problems in other countries.

**Comment by daniel-eder** [comment]
@craftbyte @stefanb thank you! We've got it on our radar and will look into merging it ASAP (capacity is a bit lower due to holiday season)

**Review by MykhailoNester — APPROVED** [review]

**Comment by craftbyte** [comment]
@daniel-eder since we have the approval now, can this be merged?

**Comment by daniel-eder** [comment]
@MykhailoNester see above - when do we plan to merge?

**Pull request merged**
